### ISSUE TITLE
Table View 작성하기 / Seat값 받아오기 / 구글맵 연동하기

### ISSUE THREAD

**Issue by kcross4** [ProjectInTheClass/YogiPC#1]
1.Model Class 에 작성된 내용을 바탕으로 초기 템플릿을 바탕으로한 Table View 만들기
2.Seat값 받아오는 방법 및 구현 - 50%
3.구글맵 연동하기

**Comment by binDongKim** [comment]
마일스톤 및 다른 이슈들로 처리함
