### ISSUE TITLE
pc방 정보화면에서 탭 정보

### ISSUE THREAD

**Issue by binDongKim** [ProjectInTheClass/YogiPC#18]
- 가격 | 정보 탭순으로
- 가격탭에는 피시방별 정액제 등의 정보

**Comment by ryj0902** [comment]
탭 순서 조정
#adc12c020cdd58229a1640a2e7f612ea7b6d9c86

**Comment by ryj0902** [comment]
구현완료

TableView로 구현
TableView와 Cell은 투명하여 배경이 보임
Cell 구분선을 없앰

Commit : 4706bd6f9015519b10789045627ce8f38b28db65
