### ISSUE TITLE
Loading image 띄워주기

### ISSUE THREAD

**Issue by ryj0902** [ProjectInTheClass/YogiPC#6]
PC방 좌석정보를 서버에서 받는 과정이 async로 이루어지는데
데이터를 받아오는동안 loading과 관련된 이미지를 띄우거나
view가 load되는걸 늦추는 방식을 추가할 필요가 있음

**Comment by ryj0902** [comment]
최초에 PC방 정보를 받아올 때에는 Loading화면을 띄울 수 있도록 만들었습니다만
문제는 데이터가 연결되지 않은 상태(unreachable) - 여기서는 와이파이를 끈 상태에서 와이파이를 다시 켜도 query는 이미 http request가 인터넷이 연결되지 않았다고 할 뿐, 정보를 제대로 받아오지 못하고 무한 Loading에 빠지는 것으로 보입니다.
관련된 문제는 기존에 시도하던 것과는 다른 새로운 접근방식이 필요해 보입니다.
Commit : 8843949398479ba34642634be2e6df13fb26ea57

**Comment by binDongKim** [comment]
근데 와이파이를 다시 켠상태에서, 새로고침(다시 running)해도 데이터 못불러온다는거야? 보통 일반 앱들 구동될때도 네트워크 끊긴상태면, 네트워크 연결이 안되어있다고 나오다가도 re-loading하면 다시 나오지 않나해서

**Comment by ryj0902** [comment]
좋은 지적이다!
그래서 해결했다!

viewDidLoad에 맞춰 인터넷 연결 상태를 알려주는 alert를 던져주고
1. PC방 정보를 '한번' 받아올 때까지 query를 반복
2. PC방 좌석정보는 viewWillDisappear할 때까지 query를 반복

문제는 2번 상황에서 인터넷 연결이 중간에 끊길 경우 실시간으로 좌석 정보를 받아오지 못한다는 사실을 사용자가 알 수 없다는 점인데....
이 부분은 NavigationBar의 우측 상단에 인터넷 연결 여부를 표기해주는 아이콘을 붙이면 될 듯 싶은데...
다음 작업에서 이 부분을 구현할 수 있도록 해보겠습니다-

Commit : 05eaed6019284f2e5b81a85415fed84c6838bf74

**Comment by ryj0902** [comment]
좌석 정보를 받아오는 view를 볼 때, 처음에 인터넷이 연결되어 있지 않으면 Alert를 하는 대신 적절한 이미지를 띄우는 형식으로 수정하였습니다.
아직까지는 좌석 정보를 '한번' 받아온 이후에는, 인터넷이 끊겨서 실시간으로 좌석정보를 받아오지 못해도 사용자에게 알려주는 UI는 구현되지 않았습니다. 이 부분에 대해서는 UI/UX를 정리할 때 의견을 나눌 필요성이 있어 보입니다.
구한 이미지가 작은 아이콘이어서 확대시 깨지는 현상이 발생하고있는데, 적절한 이미지를 구해 교체하면 좋을 것 같습니다.

Commit : 11b1874b14f0dcbdc157639db8a1a6c5de6321c5

**Comment by ryj0902** [comment]
좌석정보를 보여주는 Loading 이미지는 다음과 같습니다.
1. 인터넷이 연결되지 않았을 경우 disconnect 화면 표시
2. 인터넷이 연결 되어 좌석정보를 받아오는 도중 - activity indicator가 표시
